// Generated by gencpp from file srvclint/first.msg
// DO NOT EDIT!


#ifndef SRVCLINT_MESSAGE_FIRST_H
#define SRVCLINT_MESSAGE_FIRST_H

#include <ros/service_traits.h>


#include <srvclint/firstRequest.h>
#include <srvclint/firstResponse.h>


namespace srvclint
{

struct first
{

typedef firstRequest Request;
typedef firstResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct first
} // namespace srvclint


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srvclint::first > {
  static const char* value()
  {
    return "e208a1c5d9d170c032febd9b600898e8";
  }

  static const char* value(const ::srvclint::first&) { return value(); }
};

template<>
struct DataType< ::srvclint::first > {
  static const char* value()
  {
    return "srvclint/first";
  }

  static const char* value(const ::srvclint::first&) { return value(); }
};


// service_traits::MD5Sum< ::srvclint::firstRequest> should match
// service_traits::MD5Sum< ::srvclint::first >
template<>
struct MD5Sum< ::srvclint::firstRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srvclint::first >::value();
  }
  static const char* value(const ::srvclint::firstRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvclint::firstRequest> should match
// service_traits::DataType< ::srvclint::first >
template<>
struct DataType< ::srvclint::firstRequest>
{
  static const char* value()
  {
    return DataType< ::srvclint::first >::value();
  }
  static const char* value(const ::srvclint::firstRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srvclint::firstResponse> should match
// service_traits::MD5Sum< ::srvclint::first >
template<>
struct MD5Sum< ::srvclint::firstResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srvclint::first >::value();
  }
  static const char* value(const ::srvclint::firstResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srvclint::firstResponse> should match
// service_traits::DataType< ::srvclint::first >
template<>
struct DataType< ::srvclint::firstResponse>
{
  static const char* value()
  {
    return DataType< ::srvclint::first >::value();
  }
  static const char* value(const ::srvclint::firstResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRVCLINT_MESSAGE_FIRST_H
