// Generated by gencpp from file srvclint/firstRequest.msg
// DO NOT EDIT!


#ifndef SRVCLINT_MESSAGE_FIRSTREQUEST_H
#define SRVCLINT_MESSAGE_FIRSTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srvclint
{
template <class ContainerAllocator>
struct firstRequest_
{
  typedef firstRequest_<ContainerAllocator> Type;

  firstRequest_()
    : num(0)  {
    }
  firstRequest_(const ContainerAllocator& _alloc)
    : num(0)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::srvclint::firstRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srvclint::firstRequest_<ContainerAllocator> const> ConstPtr;

}; // struct firstRequest_

typedef ::srvclint::firstRequest_<std::allocator<void> > firstRequest;

typedef boost::shared_ptr< ::srvclint::firstRequest > firstRequestPtr;
typedef boost::shared_ptr< ::srvclint::firstRequest const> firstRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srvclint::firstRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srvclint::firstRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srvclint::firstRequest_<ContainerAllocator1> & lhs, const ::srvclint::firstRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srvclint::firstRequest_<ContainerAllocator1> & lhs, const ::srvclint::firstRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srvclint

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::srvclint::firstRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvclint::firstRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvclint::firstRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvclint::firstRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvclint::firstRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvclint::firstRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srvclint::firstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57d3c40ec3ac3754af76a83e6e73127a";
  }

  static const char* value(const ::srvclint::firstRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57d3c40ec3ac3754ULL;
  static const uint64_t static_value2 = 0xaf76a83e6e73127aULL;
};

template<class ContainerAllocator>
struct DataType< ::srvclint::firstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srvclint/firstRequest";
  }

  static const char* value(const ::srvclint::firstRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srvclint::firstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n"
;
  }

  static const char* value(const ::srvclint::firstRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srvclint::firstRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct firstRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srvclint::firstRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srvclint::firstRequest_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRVCLINT_MESSAGE_FIRSTREQUEST_H
