// Generated by gencpp from file srvclint/primeResponse.msg
// DO NOT EDIT!


#ifndef SRVCLINT_MESSAGE_PRIMERESPONSE_H
#define SRVCLINT_MESSAGE_PRIMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srvclint
{
template <class ContainerAllocator>
struct primeResponse_
{
  typedef primeResponse_<ContainerAllocator> Type;

  primeResponse_()
    {
    }
  primeResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::srvclint::primeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srvclint::primeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct primeResponse_

typedef ::srvclint::primeResponse_<std::allocator<void> > primeResponse;

typedef boost::shared_ptr< ::srvclint::primeResponse > primeResponsePtr;
typedef boost::shared_ptr< ::srvclint::primeResponse const> primeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srvclint::primeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srvclint::primeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace srvclint

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::srvclint::primeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srvclint::primeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvclint::primeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srvclint::primeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvclint::primeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srvclint::primeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srvclint::primeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::srvclint::primeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::srvclint::primeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srvclint/primeResponse";
  }

  static const char* value(const ::srvclint::primeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srvclint::primeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::srvclint::primeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srvclint::primeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct primeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srvclint::primeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::srvclint::primeResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SRVCLINT_MESSAGE_PRIMERESPONSE_H
